### ISSUE TITLE
Disabling multidimensional scrolling

### ISSUE THREAD

**Issue by plastus** [nlampi/SwiftGridView#10]
I'm trying various things using SwiftGridView and was wondering if there's an easy way to disable multidimensional? I know that UICollectionView by default only allows scrolling in one direction at a time, but with this framework you can pan around freely. Curious to know if there's an easy way to enable default behavior of single axis scrolling?

If someone could point me in the right direction I'd really appreciate it!

Thanks!

**Comment by nlampi** [comment]
Hi plastus,
Can you test out version 0.3.4 for the added property `isDirectionalLockEnabled`? This will give the scroll direction locking you are looking for.
Thanks

**Comment by plastus** [comment]
Hi nlampi,

Thanks, I was just going to post an update that I found out about this property! Appreciate you incorporating it into the library. Looks like it does exactly what I was thinking of; locking direction of scrolling to one axis even if you deviate a little bit during the scroll but otherwise allows deliberate diagonal scroll action.

Thanks again!
