### ISSUE TITLE
dataGridView:gridFooterViewForColumn is not truly optional

### ISSUE THREAD

**Issue by robcecil** [nlampi/SwiftGridView#12]
The protocol func is marked as optional, but without an implementation, it will crash.

Shouldn't the Grid implementation not assume the SwiftGridViewDataSource implementation will actually use this?

**Comment by nlampi** [comment]
Hi @robcecil 
Can you provide some more details on this (iOS version, etc) Can you also make sure that you are not passing a height for the footer (heightForGridFooterInDataGridView)?

**Comment by robcecil** [comment]
Been just modifiying your example and trying to simplify it down (removing footer, etc).

So when I comment out the heightForGridFooterInDataGridView implementation, it works.
