### ISSUE TITLE
What is the equivalent of "Frozen Rows" ?

### ISSUE THREAD

**Issue by robcecil** [nlampi/SwiftGridView#13]
What if I have only one section, and I want to define multiple frozen rows?

Thanks

**Comment by nlampi** [comment]
Currently there isn't an ability to add frozen rows. This could definitely be an enhancement that can be added though.

**Comment by nlampi** [comment]
I have pushed a new version 0.3.5 which adds the datasource numberOfFrozenRowsInSection method call. Can you test out and let me know if you have any issues?

**Comment by robcecil** [comment]
Ok, will do thanks

**Comment by robcecil** [comment]
Nathan, this works pretty well.

Question:

If I turn off section headers & footers and Grid headers & footers in the sample:

   ```
 func heightForGridHeaderInDataGridView(_ dataGridView: SwiftGridView) -> CGFloat {
        
        return 0
    }
    
    func heightForGridFooterInDataGridView(_ dataGridView: SwiftGridView) -> CGFloat {
        
        return 0
    }
    
    func dataGridView(_ dataGridView: SwiftGridView, heightOfHeaderInSection section: Int) -> CGFloat {
        
        return 0
    }
    
    func dataGridView(_ dataGridView: SwiftGridView, heightOfFooterInSection section: Int) -> CGFloat {
        
        return 0
    }
```

How would I style the frozen rows & columns differently? cellAtIndexPath?

**Comment by nlampi** [comment]
Yes I would either change the style of the cell for those index paths, or have a separate cell class for those cells. Either way can be used to update the look/feel.
