### ISSUE TITLE
Add UICollectionView.registerNib methods

### ISSUE THREAD

**Issue by dnn1s** [nlampi/SwiftGridView#17]
I can't see a possibility to use a xib file for designing a cell, but I think it should be made possible. What do you think?

**Comment by nlampi** [comment]
makes sense, will do for next release.

**Comment by nlampi** [comment]
Added the ability to use NIBs for both cells and reusable views with the latest release (0.5.0). The updated example project shows a basic usage.
Note that the cell/view registration methods were updated to use method overloading to clean up the interface a little.
