### ISSUE TITLE
Move space on top grid

### ISSUE THREAD

**Issue by manhlt1990** [nlampi/SwiftGridView#21]
![img_1634](https://user-images.githubusercontent.com/18260709/27421835-3e5ea8e2-5756-11e7-8e5f-3fdee529a3cf.PNG)

**Comment by nlampi** [comment]
Hi @manhlt1990 
With this issue it is hard to tell the source of the problem. Can you change your viewcontroller property for automaticallyAdjustsScrollViewInsets to NO? ("Adjust Scroll View Insets" under Layout if you're using a Storyboard)
Thanks
