### ISSUE TITLE
Cannot have different heights for separate rows?

### ISSUE THREAD

**Issue by lmljonathan** [nlampi/SwiftGridView#24]
When giving different heights for heightOfRowAtIndexPaths, some grid rows overlap and mess up. Can there only be one constant height for all rows throughout the grid?

**Comment by nlampi** [comment]
Something seems off with the positioning of rows here, will investigate.

**Comment by nlampi** [comment]
Sorry for the delay, but please test using the latest 0.5.1 which fixes this issue of row positioning.

**Comment by lmljonathan** [comment]
Works great now!
