### ISSUE TITLE
Can we create a group header. For reference I have attached screenshot.

### ISSUE THREAD

**Issue by sivakspt** [nlampi/SwiftGridView#3]
![screen shot 2016-12-06 at 1 01 32 pm](https://cloud.githubusercontent.com/assets/4215814/20916896/5fde3962-bbb4-11e6-90bb-b3f1f43cb93c.png)

I would like to know if we can create a header like the one in the screen shot.

**Comment by nlampi** [comment]
This is a good question. It is on my list of items to approach. I will test out a few things to see what is currently possible.

**Comment by sivakspt** [comment]
Do we have any update on this on this can be implemented into Grid.

**Comment by nlampi** [comment]
I have added the ability to add a grouped header view which will allow you to achieve the above requirement (v 0.3.1). Currently the height of the grouped header will be split with the existing column headers. Please test and let me know if you have any issues.

**Comment by sivakspt** [comment]
This is working fine. I am doing more testing on this feature. In the mean time I have found few memory issues. I will create a new issue we can work on it.
