### ISSUE TITLE
Grouping header issue

### ISSUE THREAD

**Issue by vlapra** [nlampi/SwiftGridView#32]
There is an error at SwiftGridView file at line 823. It takes care only about first two columns of a group. 

`            for column in grouping[0] ... grouping[1] {
                colWidth += self.delegate!.dataGridView(self, widthOfColumnAtIndex: column)
            }`

It should be

`            for column in grouping {
                colWidth += self.delegate!.dataGridView(self, widthOfColumnAtIndex: column)
            }`

**Comment by nlampi** [comment]
Column grouping works off of the column index for the first and last column of the group. This adds up the width for all column in between. 
I see now that the documentation/error checks for this might be insufficient and I can add some more for that.

**Comment by vlapra** [comment]
Thanks a lot. It was my misunderstanding:(

Great job!

Thanks V. 


20. 2. 2018 v 0:04, Nathan Lampi <notifications@github.com>:
