### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by robcecil** [nlampi/SwiftGridView#37]
I was examining the memory footprint of my app over time, as I performed some central functions that involve creating instances of SwiftGridView. In my app, I support multiple instances open, through a tab interface:

![simulator screen shot - ipad air 2 - 2018-06-20 at 12 45 32](https://user-images.githubusercontent.com/1533670/41672416-df5153d6-7487-11e8-8a42-0004a012d964.png)

In my test, I opened four of my 'views', each of which corresponds to an instance of a SwiftGridView. Then I closed each of them, for an empty environment. 

Then I invoked the memory graph tool in Xcode. I searched to verify that my pertinent class instances were not leaked (in my case, GridViewController and GridViewModel). They were cleaned up.

BUT I noticed that all four instances of the SwiftGridView (and corresponding SwiftGridLayout) were still around, as well as many hundreds of my UICollectionViewCell derivatives (a modified BasicTextCell, plus some sibling classes).

<img width="1693" alt="screen shot 2018-06-19 at 4 55 35 pm" src="https://user-images.githubusercontent.com/1533670/41672604-5359e8ec-7488-11e8-9706-828f9443071d.png">

<img width="1648" alt="screen shot 2018-06-19 at 9 13 19 pm" src="https://user-images.githubusercontent.com/1533670/41672615-57424b0c-7488-11e8-965b-b02e9786cf63.png">

<img width="1662" alt="screen shot 2018-06-19 at 9 13 24 pm" src="https://user-images.githubusercontent.com/1533670/41672616-59c183a2-7488-11e8-8fee-6e60139e578e.png">

**Comment by nlampi** [comment]
I have pushed a new version (0.6.4) which fixes a reference that should have been weak. When testing removal/allocating I see that memory sticks where expected on my end. Can you test and see if you are still seeing the same issue?

**Comment by robcecil** [comment]
Thanks. Will test shortly

**Comment by robcecil** [comment]
I repeated my test and I didn't find any leaked instances of either the Grid or the layout.
