### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by combes** [nlampi/SwiftGridView#4]
Attempted to build the framework but it appears there is a hard-coded path, although I don't see this path in the project...
`(null): error: /Users/nlampi/Library/Developer/Xcode/DerivedData/SwiftGridView-cvxfbdfxwyeinydiohsdltfggzll/Build/Products/Debug-iphoneos/SwiftGridView.framework: No such file or directory`

Trying to build and run the example.

**Comment by nlampi** [comment]
Please update to the latest (0.3.1) and try to build again.
