### ISSUE TITLE
Trying to programmatically create SwiftGridView crashes

### ISSUE THREAD

**Issue by sedwo** [nlampi/SwiftGridView#46]
![image](https://user-images.githubusercontent.com/1434449/55332892-3a1db900-5464-11e9-8e83-c50ac690f197.png)

**Comment by nlampi** [comment]
This is generally caused when you don't have a dataSource set. Can you make sure that it is set and conforms to the SwiftGridViewDataSource protocol?

**Comment by sedwo** [comment]
I understand.  But programmatically I need to instantiate the `SwiftGridView` object before I am able to set its delegates.  And the crash occurs during the init process.

Crash example.
```
var gridDataSource = PrettyDataSource()
var gridDelegate = PrettyDelegate()

let prettyGridView = SwiftGridView(frame: CGRect(x: 0, y: 0, width: 0, height: 200))

prettyGridView.delegate = gridDelegate
prettyGridView.dataSource = gridDataSource
```

**Comment by sedwo** [comment]
My bad.
I was trying to initialize everything inside a closure.

Good job on this control.  👍

**Comment by nlampi** [comment]
Ah, good to have details on what situations cause errors. Thanks!
