### ISSUE TITLE
is it possible to hide columns ?

### ISSUE THREAD

**Issue by SogoGolf** [nlampi/SwiftGridView#48]
hi, thanks for the great component. is it possible to selectively hide columns via the api ?

**Comment by nlampi** [comment]
Hi @SogoGolf, right now there's no built in way to hide columns. You could change the visible columns by reloading the data grid and changing the returned column values in the data source. This would not be animated in any way though. Can you provide some context around the intended use case? This would help determine if this is something that could be added as an enhancement.
Thanks

**Comment by SogoGolf** [comment]
Hey, that's cool. Yes that's what I've done just swap out different data sets, which is fine. For now let's leave it as is, I'll reopen the issue if need be in future
