### ISSUE TITLE
Remove Section Header/Footer

### ISSUE THREAD

**Issue by hongvuxuan** [nlampi/SwiftGridView#50]
Hi @nlampi Is there any ways to remove Section Header/Footer? At this time, I hide these by change height to 0. Please advise.

**Comment by nlampi** [comment]
Hi @hongvuxuan, if you don't need section header/footer at all, just don't implement the height method. If you need to disable for a specific section, then you are correct to return a height 0. This will prevent the grid from loading the view.

**Comment by hongvuxuan** [comment]
Got it, thanks @nlampi
