### ISSUE TITLE
weird behavior

### ISSUE THREAD

**Issue by watemotion** [nlampi/SwiftGridView#61]
I'm getting weird behavior with the Universal Example when setting

self.dataGridView.stickySectionHeaders = false

While scrolling, the rows (0, 0, 0) and (0, 0, 1) are frized over the collectionView leaving a white space on it.

![IMG_82C1373B1591-1](https://user-images.githubusercontent.com/20820956/107774725-aa274680-6d3f-11eb-98c0-de5904ea9feb.jpeg)

**Comment by nlampi** [comment]
Fixed with release v0.7.5
Thanks for reporting!
