### ISSUE TITLE
Simulator returning erratic index from didSelectCellAtIndexPath

### ISSUE THREAD

**Issue by sedwo** [nlampi/SwiftGridView#63]
I have a simple view with 15 rows and 8 columns.  As you can see by the video, tapping on various columns seems to result with receiving [0, 14], when in fact my cursor is on [0, 7].  🤔

I randomly scroll around and try other cells, and when I even try to tap on the actual [0, 14] cell location, I get no response, or a random delay.

_BUT...._ trying on an actual hardware iPhone doesn't seem to produce this issue.  ¯\_(ツ)_/¯

Using Xcode 12.5 with iOS 14.5

https://user-images.githubusercontent.com/1434449/116630751-d192b600-a921-11eb-99a6-74b723222abd.mp4

**Comment by sedwo** [comment]
Seems like an Xcode and simulator restart might have stabilized it.  : \

I'll monitor it.

**Comment by nlampi** [comment]
Haven't been able to reproduce yet either. I'll continue to test with Xcode 12.5 to see for any other issues as well.

**Comment by nlampi** [comment]
Closing for now to keep things clean. I'll keep an eye out, but let me know if you find a way to recreate the issue.
