### ISSUE TITLE
Bug with wrong height variable used for grouping

### ISSUE THREAD

**Issue by sivakspt** [nlampi/SwiftGridView#8]
case SwiftGridElementKindGroupedHeader:
            let grouping = self.groupedColumns[indexPath.item]
            
            for column in grouping[0] ... grouping[1] {
                colWidth += self.delegate!.dataGridView(self, widthOfColumnAtIndex: column)
            }
            
            if let delegateHeight = self.delegate?.dataGridView?(self, heightOfHeaderInSection: indexPath.section) {
                if(delegateHeight > 0) {
                    rowHeight = delegateHeight
                }
            }
            break

This code can cause problems since we are using "heightOfHeaderInSection" but the grouping is done for grid header not to the section header.

**Comment by nlampi** [comment]
Another good catch. Updated to properly work using the grid header height. Please test using 0.3.3.
